#:schema node_modules/wrangler/config-schema.json
name = "viabrisbane"
compatibility_date = "2024-12-05"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./dist"

[vars]
NODE_VERSION = 18.20.8
UPDATED_DATE = "2025-02-05T00:00:00Z"
PUBLIC_GOOGLE_MAPS_API_KEY= "AIzaSyCCQ8ZqAJjDm1O-ToZopbRlv4-zg9jpph4"
PUBLIC_BASE_URL= "https://www.viabrisbane.com"


[[d1_databases]]
binding = "DB"
database_name = "viabrisbane"
database_id = "eaa7da18-d48c-4968-8672-20d290320793"
preview_database_id = "2066c52d-b255-40b2-bfa0-56dc285617d4"

[env.preview]
name = "preview"
[[env.preview.d1_databases]]
binding = "DB"
database_name = "viabrisbane-preview"
database_id = "2066c52d-b255-40b2-bfa0-56dc285617d4"

[[env.preview.vars]]
UPDATED_DATE = "2025-02-05T00:00:00Z"
PUBLIC_GOOGLE_MAPS_API_KEY= "AIzaSyCCQ8ZqAJjDm1O-ToZopbRlv4-zg9jpph4"
PUBLIC_BASE_URL= "https://develop-astro.viabrisbane.pages.dev"