#:schema node_modules/wrangler/config-schema.json
name = "viabrisbane-astro"
compatibility_date = "2024-12-05"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "viabrisbane"
database_id = "11e8ae8b-1592-46e8-b0fd-09d1b0c1e52c"
preview_database_id = "DB"