CREATE TABLE `parking_meters` (
	`ObjectId` integer PRIMARY KEY NOT NULL,
	`METER_NO` integer,
	`CATEGORY` text(255),
	`STREET` text(255),
	`SUBURB` text(255),
	`MAX_STAY_HRS` text(255),
	`RESTRICTIONS` text(255),
	`OPERATIONAL_DAY` text(255),
	`OPERATIONAL_TIME` text(255),
	`TAR_ZONE` text(255),
	`TAR_RATE_WEEKDAY` real,
	`TAR_RATE_AH_WE` real,
	`LOC_DESC` text(255),
	`VEH_BAYS` integer,
	`MC_BAYS` integer,
	`MC_RATE` real,
	`LONGITUDE` real,
	`LATITUDE` real,
	`MOBILE_ZONE` integer,
	`MAX_CAP_CHG` text(255),
	`geo_shape` text(255),
	`geo_point_2d` text(255),
	`VEH_BAYS_INT` integer
);
